### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by iebmw** [ievazzade/gh-actions#1]
I think it looks better if the main title is a bit more orange.

The styling rule could be changed lik this:

```css
h1 {
  color: #efa82e;
}
```
